-- MySQL Script generated by MySQL Workbench
-- lun 27 mar 2023 19:20:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Bibliotecario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bibliotecario` (
  `idBibliotecario` VARCHAR(45) NOT NULL,
  `BibliotecarioNombre` VARCHAR(150) NOT NULL,
  `BibliotecarioTelefono` VARCHAR(15) NULL,
  `BibliotecarioClave` VARCHAR(45) NULL,
  PRIMARY KEY (`idBibliotecario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Libro` (
  `idLibro` INT NOT NULL,
  `LibroAutor` VARCHAR(150) NULL,
  `LibroNombre` VARCHAR(255) NOT NULL,
  `LibroEdicion` VARCHAR(45) NULL,
  `LibroPaginas` VARCHAR(5) NULL,
  `LibroGenero` VARCHAR(45) NULL,
  PRIMARY KEY (`idLibro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` VARCHAR(45) NOT NULL,
  `UsuarioNombre` VARCHAR(255) NULL,
  `UsuarioTipoIdentificacion` VARCHAR(10) NULL,
  `UsuarioTelefono` VARCHAR(15) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LibrosPrestados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LibrosPrestados` (
  `idLibrosPrestados` INT NOT NULL AUTO_INCREMENT,
  `LibrosPrestadosSalida` VARCHAR(45) NULL,
  `LibrosPrestadosLlegada` VARCHAR(45) NULL,
  `Bibliotecario_idBibliotecario` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` VARCHAR(45) NOT NULL,
  `Libro_idLibro` INT NOT NULL,
  PRIMARY KEY (`idLibrosPrestados`),
  INDEX `fk_LibrosPrestados_Bibliotecario1_idx` (`Bibliotecario_idBibliotecario` ASC) VISIBLE,
  INDEX `fk_LibrosPrestados_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_LibrosPrestados_Libro1_idx` (`Libro_idLibro` ASC) VISIBLE,
  CONSTRAINT `fk_LibrosPrestados_Bibliotecario1`
    FOREIGN KEY (`Bibliotecario_idBibliotecario`)
    REFERENCES `mydb`.`Bibliotecario` (`idBibliotecario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LibrosPrestados_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LibrosPrestados_Libro1`
    FOREIGN KEY (`Libro_idLibro`)
    REFERENCES `mydb`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ListaNegra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ListaNegra` (
  `idListaNegra` INT NOT NULL,
  `LibrosPrestados_idLibrosPrestados` INT NOT NULL,
  PRIMARY KEY (`idListaNegra`),
  INDEX `fk_ListaNegra_LibrosPrestados1_idx` (`LibrosPrestados_idLibrosPrestados` ASC) VISIBLE,
  CONSTRAINT `fk_ListaNegra_LibrosPrestados1`
    FOREIGN KEY (`LibrosPrestados_idLibrosPrestados`)
    REFERENCES `mydb`.`LibrosPrestados` (`idLibrosPrestados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
